### ISSUE TITLE
datamodel.types is not iterable

### ISSUE THREAD

**Issue by TMInnovations** [unlight/prisma-nestjs-graphql#106]
The generation fails if datamodel.types is undefined (which happens when 0 `type` blocks are defined in the prisma schema => https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#composite-type-unique-constraints. & when using Postgres as underlying database it's not possible to define type blocks).

```
TypeError: datamodel.types is not iterable
    at generate (C:\...\node_modules\prisma-nestjs-graphql\index.js:2046:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.onGenerate (C:\...\node_modules\prisma-nestjs-graphql\index.js:2099:5)
    at async LineStream.<anonymous> (C:\...\node_modules\prisma-nestjs-graphql\node_modules\@prisma\generator-helper\dist\generatorHandler.js:36:24)
```

I think I already found the problematic line:
https://github.com/unlight/prisma-nestjs-graphql/blob/651b08baf42122b0d3d47f7e37452c714314c3c7/src/generate.ts#L132

**Comment by TMInnovations** [comment]
#107 added PR
