### ISSUE TITLE
[DecimalError] Invalid argument: undefined

### ISSUE THREAD

**Issue by asanovr** [unlight/prisma-nestjs-graphql#113]
Hello, I'm facing an error with the decimal type, the prisma-graphql-type-decimal package has already been installed.
Error trace
```
Error: [DecimalError] Invalid argument: undefined
    at new Decimal (/app/node_modules/@prisma/client/runtime/index.js:38450:13)
    at TransformOperationExecutor.transform (/app/node_modules/src/TransformOperationExecutor.ts:160:22)
    at TransformOperationExecutor.transform (/app/node_modules/src/TransformOperationExecutor.ts:333:33)
    at ClassTransformer.plainToInstance (/app/node_modules/src/ClassTransformer.ts:77:21)
    at Object.plainToClass (/app/node_modules/src/index.ts:71:27)
    at ValidationPipe.transform (/app/node_modules/@nestjs/common/pipes/validation.pipe.js:51:39)
    at /app/node_modules/@nestjs/core/pipes/pipes-consumer.js:16:33
```

Graphql mutation
```
mutation {
	createSalary(input: {
		currency: {
			connect: {
				id: 1
			}
		},
		from: 10.10,
		to: 15.15,
		schedule: MONTH,
		type: CONTRACT
	}) {
		id
	}
}
```

Part of scheme
```
generator client {
  provider = "prisma-client-js"
}

generator nestgraphql {
  provider = "prisma-nestjs-graphql"
  output   = "../src/@generated/prisma-nestjs-graphql"
}

datasource db {
  provider = "mysql"
  url          = env("DATABASE_URL")
}

model Salary {
  id         Int            @id @default(autoincrement()) @db.UnsignedInt
  type       SalaryType
  schedule   SalarySchedule
  currencyId Int            @db.UnsignedInt
  from       Decimal        @db.Decimal(15, 2)
  to         Decimal        @db.Decimal(15, 2)
  createdAt  DateTime       @default(now())
  updatedAt  DateTime       @updatedAt

  job Job[]
  currency Currency @relation(fields: [currencyId], references: [id], onDelete: Restrict)

  @@map("salaries")
}
```
Part of resolver
```
  @UseGuards(GqlAuthGuard)
  @Mutation(() => SalaryModel)
  async createSalary(
    @Args('input') input: SalaryCreateInput,
    @Info() info: GraphQLResolveInfo,
  ): Promise<Salary> {
    return this.salariesService.createSalary(input);
  }
```

Generated input
```
import { Field } from '@nestjs/graphql';
import { InputType } from '@nestjs/graphql';
import { SalaryType } from '../prisma/salary-type.enum';
import { SalarySchedule } from '../prisma/salary-schedule.enum';
import { Decimal } from '@prisma/client/runtime';
import { GraphQLDecimal } from 'prisma-graphql-type-decimal';
import { JobCreateNestedManyWithoutSalaryInput } from '../job/job-create-nested-many-without-salary.input';
import { CurrencyCreateNestedOneWithoutSalaryInput } from '../currency/currency-create-nested-one-without-salary.input';

@InputType()
export class SalaryCreateInput {

    @Field(() => SalaryType, {nullable:false})
    type!: keyof typeof SalaryType;

    @Field(() => SalarySchedule, {nullable:false})
    schedule!: keyof typeof SalarySchedule;

    @Field(() => GraphQLDecimal, {nullable:false})
    from!: Decimal;

    @Field(() => GraphQLDecimal, {nullable:false})
    to!: Decimal;

    @Field(() => Date, {nullable:true})
    createdAt?: Date | string;

    @Field(() => Date, {nullable:true})
    updatedAt?: Date | string;

    @Field(() => JobCreateNestedManyWithoutSalaryInput, {nullable:true})
    job?: JobCreateNestedManyWithoutSalaryInput;

    @Field(() => CurrencyCreateNestedOneWithoutSalaryInput, {nullable:false})
    currency!: CurrencyCreateNestedOneWithoutSalaryInput;
}
```

**Comment by unlight** [comment]
Big issue. It's weird that it's just now found.

**Comment by unlight** [comment]
@asanovr 
Please, try new version from `@next` channel, also note you need to update `prisma-graphql-type-decimal` to latest version(2.0.2)

**Comment by asanovr** [comment]
@unlight  Thank you! 
The bug was fixed in the root params, but still appears in a nested query.
I've created a simple repository for bug reproduction https://github.com/asanovr/-prisma-nestjs-graphql-decimal-test#test-nested-object

**Comment by unlight** [comment]
Please, check new version

**Comment by asanovr** [comment]
@unlight It's working as expected, thank you!

**Comment by solispauwels** [comment]
Hello, 

This is still falling when a field is otional and is not been sent. So its value will be undefined and class trasform will try to use transformToDecimal

**Comment by asanovr** [comment]
@unlight Hi, I faced with another bug with Decimal
Repository for a bug reproduction https://github.com/asanovr/-prisma-nestjs-graphql-decimal-test

Error trace
```
[Nest] 84612  - 08/25/2022, 3:28:32 PM   ERROR [ExceptionsHandler] [DecimalError] Invalid argument: undefined
Error: [DecimalError] Invalid argument: undefined
    at new Decimal (/Users/asanovr/Dev/-prisma-nestjs-graphql-decimal-test/node_modules/@prisma/client/runtime/index.js:38450:13)
    at TransformOperationExecutor.transform (/Users/asanovr/Dev/-prisma-nestjs-graphql-decimal-test/node_modules/src/TransformOperationExecutor.ts:160:22)
    at TransformOperationExecutor.transform (/Users/asanovr/Dev/-prisma-nestjs-graphql-decimal-test/node_modules/src/TransformOperationExecutor.ts:333:33)
    at /Users/asanovr/Dev/-prisma-nestjs-graphql-decimal-test/node_modules/src/TransformOperationExecutor.ts:79:30
    at Array.forEach (<anonymous>)
    at TransformOperationExecutor.transform (/Users/asanovr/Dev/-prisma-nestjs-graphql-decimal-test/node_modules/src/TransformOperationExecutor.ts:44:24)
    at TransformOperationExecutor.transform (/Users/asanovr/Dev/-prisma-nestjs-graphql-decimal-test/node_modules/src/TransformOperationExecutor.ts:333:33)
    at TransformOperationExecutor.transform (/Users/asanovr/Dev/-prisma-nestjs-graphql-decimal-test/node_modules/src/TransformOperationExecutor.ts:333:33)
    at TransformOperationExecutor.transform (/Users/asanovr/Dev/-prisma-nestjs-graphql-decimal-test/node_modules/src/TransformOperationExecutor.ts:333:33)
    at TransformOperationExecutor.transform (/Users/asanovr/Dev/-prisma-nestjs-graphql-decimal-test/node_modules/src/TransformOperationExecutor.ts:333:33)
```

Graphql mutation
```
mutation {
  updateEmployee(
    id: "1"
    input: {
      salaryHistory: {
        update: {
          history: {
            createMany: { data: [{ from: 1, to: 1, year: 1 }] }
            update: []
          }
        }
      }
    }
  ) {
    id
  }
}
```

Scheme
```
model Employee {
  id              String         @id @default(cuid())
  salaryHistoryId String?        @unique
  salaryHistory   SalaryHistory? @relation(name: "employeeSalaryHistory", fields: [salaryHistoryId], references: [id], onDelete: SetNull)

  @@map("employees")
}

model SalaryHistory {
  id         String   @id @default(cuid())
  currencyId String   @db.Char(3)
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt

  history               SalaryHistoryRecord[]
  employeeSalaryHistory Employee?             @relation(name: "employeeSalaryHistory")

  @@map("salary_history")
}

model SalaryHistoryRecord {
  id              String  @id @default(cuid())
  salaryHistoryId String
  year            Int     @db.SmallInt
  from            Decimal @db.Decimal(15, 2)
  to              Decimal @db.Decimal(15, 2)

  salaryHistory SalaryHistory @relation(fields: [salaryHistoryId], references: [id], onDelete: Cascade)

  @@map("salary_history_record")
}

```

**Comment by solispauwels** [comment]
I am facing the same issue on nested relation filters.
Nested relation filters need a @Type to work but it is missing. 
Do you have a workaround suggestion? Otherwise I think I will correct this on the meanwhile by a visitor on generated files but is not ideal.

```
query myQuery{
  myQuery(
    where: { 
      myDecimal: {
        gte: "10.5" # Works fine
      },
      myRelation: {
        is: {
          myDecinal: {
            gte: "10.1" # Does not work
          }
        }
      }
  ) {
    myField
  }
}
```

**Comment by solispauwels** [comment]
Thank you very much @unlight :)
