### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kachar** [unlight/prisma-nestjs-graphql#149]
The generator succeeds in the generation but crashes at runtime  when using `"prisma": "4.7.0"` and `"@prisma/client": "4.7.0"`

```shell
[7:56:30 AM] File change detected. Starting incremental compilation...

/app/cells/graph-api/node_modules/typescript/lib/typescript.js:115822
throw e;
^

RangeError: Maximum call stack size exceeded
at resolveEntityName (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:50057:35)
at resolveTypeReferenceName (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:59348:26)
at getTypeFromTypeReference (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:59530:30)
at getTypeFromTypeNodeWorker (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:62041:28)
at getTypeFromTypeNode (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:62001:49)
at Object.map (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:638:29)
at getTypeFromUnionTypeNode (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:60353:54)
at getTypeFromTypeNodeWorker (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:62054:28)
at getTypeFromTypeNode (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:62001:49)
at tryGetTypeFromEffectiveTypeNode (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:55456:24)

Node.js v19.2.0
```

```
Exception has occurred: RangeError: Maximum call stack size exceeded
  at getResolvedMembersOrExportsOfSymbol (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:59024:53)
    at getMembersOfSymbol (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:59079:19)
    at isEmptyAnonymousObjectType (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:65891:90)
    at Object.some (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:748:25)
    at getNormalizedUnionOrIntersectionType (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:66056:73)
    at getNormalizedType (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:66042:84)
    at isRelatedTo (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:66404:30)
    at isPropertySymbolTypeRelated (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:67746:24)
    at propertyRelatedTo (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:67789:31)
    at propertiesRelatedTo (/app/cells/graph-api/node_modules/typescript/lib/typescript.js:67990:43)
```

```shell
tree @generated

....

30 directories, 2784 files
```

The app works ok with prisma `v4.6.1`

**Comment by kachar** [comment]
Possibly related to https://github.com/prisma/prisma/issues/16535

**Comment by kachar** [comment]
Looks like it is a problem with `prisma` `v4.7.0` and `v4.7.1`

Closing this issue in favor of https://github.com/prisma/prisma/issues/16600

**Comment by tavindev** [comment]
Same here with v4.7.1. Reverting to v4.6.1 solved the issue for me as well.

**Comment by kachar** [comment]
When I turned off `clientExtensions` feature the compilation was successful. Downgrading also works
