### ISSUE TITLE
Incorrect (?) Type generated for field with array of enum

### ISSUE THREAD

**Issue by chrisLovesCode** [unlight/prisma-nestjs-graphql#188]
**---- UPDATE----**

so i am able to receive an erray of enum when my type definition looks like this, which i manually did:

```
    @Field(type=> [String])
    @Validator.IsNotEmpty()
    genres: ConGenres[];
```
**BUT** PROLEM: prisma-nestjs-graphql does generate this, which will not work

```
  @Field(() => ConventionCreategenresInput, {nullable:true})
   genres?: ConventionCreategenresInput;
```
it imports Genereated convention-creategenres.input
```
import { Field } from '@nestjs/graphql';
import { InputType } from '@nestjs/graphql';
import { ConGenres } from '../prisma/con-genres.enum';

@InputType()
export class ConventionCreategenresInput {

    @Field(() => [ConGenres], {nullable:false})
    // SEEMS TO BE THE PROBLEM! :
    set!: Array<keyof typeof ConGenres>;
}
```

schema.prisma
```
generator client {
  provider = "prisma-client-js"
}

generator nestgraphql {
    provider = "node node_modules/prisma-nestjs-graphql"
    output = "../src/@generated"

    fields_Validator_from = "class-validator"
    fields_Validator_input = true
}
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Convention {
  id            String          @id @default(uuid())
  genres            ConGenres[]
  @@map("convention")
}

enum ConGenres {
  medieval
  crime
}
```

**So why is it so and what do i have to configure please? thank you so much for help. took me whole day to find it**

**---- OLD POST FOR REFERENCE----**

PROBLEM
Summary: i try to send data for a field, which value should be an array of enums (in prisma: ConGenres[]).
But it seems i have setup a field called "set", defined in the generated types from prisma-nestjs-graphql which i dont know what to do now

DETAILS:

When i try so end an array of enums from my Frontend to my graphql nestjs api, like so:

```
// FE Ajax
 const onSubmit = async (data:any) => {
        data.genres = [
            ConGenres.Crime,
            ConGenres.Medieval
         ];
            await toast.promise(
                gqlReq.conventionCreate({data}),
                { ...DEFAULT_TOAST_MESSAGE }
            )
        return;
    };

// FE fetched ConGenres enum
export enum ConGenres {
  Crime = 'crime',
  Medieval = 'medieval',
}
```

i get the following response:
```
{
    "errors": [
        {
            "message": "Variable \"$data\" got invalid value { enum: [\"crime\", \"medieval\"] } at \"data.genres\"; Field \"set\" of required type \"[ConGenres!]!\" was not provided.",
            "locations": [
                {
                    "line": 1,
                    "column": 27
                }
            ],
            "extensions": {
                "code": "BAD_USER_INPUT",
                "stacktrace": [
                    "GraphQLError: Field \"set\" of required type \"[ConGenres!]!\" was not provided.",
                    "    at coerceInputValueImpl (/api/node_modules/graphql/utilities/coerceInputValue.js:108:13)",
                    "    at coerceInputValueImpl (/api/node_modules/graphql/utilities/coerceInputValue.js:117:34)",
                    "    at coerceInputValueImpl (/api/node_modules/graphql/utilities/coerceInputValue.js:49:14)",
                    "    at coerceInputValue (/api/node_modules/graphql/utilities/coerceInputValue.js:32:10)",
                    "    at coerceVariableValues (/api/node_modules/graphql/execution/values.js:132:69)",
                    "    at getVariableValues (/api/node_modules/graphql/execution/values.js:45:21)",
                    "    at buildExecutionContext (/api/node_modules/graphql/execution/execute.js:280:63)",
                    "    at execute (/api/node_modules/graphql/execution/execute.js:116:22)",
                    "    at executeIncrementally (/api/node_modules/@apollo/server/src/incrementalDeliveryPolyfill.ts:114:17)",
                    "    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
                ]
            }
        },
        {
            "message": "Variable \"$data\" got invalid value { enum: [\"crime\", \"medieval\"] } at \"data.genres\"; Field \"enum\" is not defined by type \"ConventionCreategenresInput\".",
            "locations": [
                {
                    "line": 1,
                    "column": 27
                }
            ],
            "extensions": {
                "code": "BAD_USER_INPUT",
                "stacktrace": [
                    "GraphQLError: Field \"enum\" is not defined by type \"ConventionCreategenresInput\".",
                    "    at coerceInputValueImpl (/api/node_modules/graphql/utilities/coerceInputValue.js:134:11)",
                    "    at coerceInputValueImpl (/api/node_modules/graphql/utilities/coerceInputValue.js:117:34)",
                    "    at coerceInputValueImpl (/api/node_modules/graphql/utilities/coerceInputValue.js:49:14)",
                    "    at coerceInputValue (/api/node_modules/graphql/utilities/coerceInputValue.js:32:10)",
                    "    at coerceVariableValues (/api/node_modules/graphql/execution/values.js:132:69)",
                    "    at getVariableValues (/api/node_modules/graphql/execution/values.js:45:21)",
                    "    at buildExecutionContext (/api/node_modules/graphql/execution/execute.js:280:63)",
                    "    at execute (/api/node_modules/graphql/execution/execute.js:116:22)",
                    "    at executeIncrementally (/api/node_modules/@apollo/server/src/incrementalDeliveryPolyfill.ts:114:17)",
                    "    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
                ]
            }
        }
    ]
}
```

Generated convention-creat.input
```
import { Field } from '@nestjs/graphql';
import { InputType } from '@nestjs/graphql';
import { ConventionCreategenresInput } from './convention-creategenres.input';

@InputType()
export class ConventionCreateInput {
    @Field(() => ConventionCreategenresInput, {nullable:true})
    genres?: ConventionCreategenresInput;
}
```

Genereated convention-creategenres.input
```
import { Field } from '@nestjs/graphql';
import { InputType } from '@nestjs/graphql';
import { ConGenres } from '../prisma/con-genres.enum';

@InputType()
export class ConventionCreategenresInput {

    @Field(() => [ConGenres], {nullable:false})
    set!: Array<keyof typeof ConGenres>;
}
```

Generated con-genres.enum
```
import { registerEnumType } from '@nestjs/graphql';

export enum ConGenres {
    medieval = "medieval",
    crime = "crime",
}

registerEnumType(ConGenres, { name: 'ConGenres', description: undefined })
```

When i do the following, and add "set" obj to my FE ajax request, i get no error BUT i dont receive the data either >.<
```
     data.genres = {set:[
            ConGenres.Crime,
            ConGenres.Medieval
         ]}
```

**So what this freakin "set" all about?**
When i try to hack it manualy in my resolver, it works, so the problem is the typing stuff generated
```
    // Create convention
    @UseGuards(GqlAuthGuard, MaintenanceGuard(), RoleGuard(Role.user))
    @Mutation(() => Convention)
    async conventionCreate(
        @Usr() user: AuthUser,
        @Args('data') data: ConventionCreateInput
    ) {
        data.genres = ['crime', 'medieval']
        const created = await this.conventionService.create(
            data,
            user,
        );
        return created
    }

```

**Comment by chrisLovesCode** [comment]
UPDATED: found out it this fixed it:

```
generator nestgraphql {
    provider = "node node_modules/prisma-nestjs-graphql"
    output = "../src/@generated/dto"
    **noAtomicOperations = true**
}
```
