### ISSUE TITLE
Compatibility Issue Prisma 2.22

### ISSUE THREAD

**Issue by lukadriel7** [unlight/prisma-nestjs-graphql#30]
Hello, It seems prisma changed something in their code that breaks compatibility with this library in the version 2.22

**Comment by lukadriel7** [comment]
Some more context.
I updated my project dependencies. I could generate a graphql types files with prisma 2.21.2 but after updating to 2.22.1, I get the following error on generation
```
TypeError: Cannot get matching input type from String,String
    at getGraphqlInputType (/home/adriel/Documents/VSCode/Altea/DPI/api/node_modules/prisma-nestjs-graphql/index.js:436:9)
    at AwaitEventEmitter.inputType (/home/adriel/Documents/VSCode/Altea/DPI/api/node_modules/prisma-nestjs-graphql/index.js:538:30)
    at AwaitEventEmitter.<anonymous> (/home/adriel/Documents/VSCode/Altea/DPI/api/node_modules/await-event-emitter/lib/index.js:115:39)
    at Generator.next (<anonymous>)
    at /home/adriel/Documents/VSCode/Altea/DPI/api/node_modules/await-event-emitter/lib/index.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/home/adriel/Documents/VSCode/Altea/DPI/api/node_modules/await-event-emitter/lib/index.js:8:12)
    at AwaitEventEmitter.emit (/home/adriel/Documents/VSCode/Altea/DPI/api/node_modules/await-event-emitter/lib/index.js:108:16)
    at generate (/home/adriel/Documents/VSCode/Altea/DPI/api/node_modules/prisma-nestjs-graphql/index.js:1550:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I will also add my schema just in case

```
// This is your Prisma schema folder,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["selectRelationCount", "orderByRelation", "orderByAggregateGroup"]
}

generator nestgraphql {
  provider   = "node node_modules/prisma-nestjs-graphql"
  output     = "../src/graphql"
  emitSingle = true
}

/// Defini le sex du patient
enum SEX {
  MALE
  FEMALE
}

enum BLOODTYPE {
  O
  A
  B
  AB
}

enum RHESUS {
  POSITIVE
  NEGATIVE
}

/// Defini l'etat actuel du sejour
enum FOLDERSTATUS {
  WAITING
  READY
  OPEN
  PENDING
  CLOSED
}

/// Defini le type de dossier patient
enum FOLDERTYPE {
  EXTERNE
  OBSERVATION
  URGENCE
  HOSPITALISATION
}

/// Defini le type de l'acte effectue
enum ACTTYPE {
  RADIO
  LABORATOIRE
  MEDICAL
  INFIRMIER
  AUTRE
}

enum ADMINISTRATIONROUTE {
  ORALE
  INJECTION
  SUBLINGUALE
  RECTALE
  VAGINALE
  OCULAIRE
  AURICULAIRE
  NASALE
  INHALATION
  NEBULISATION
  CUTANEE
  TRANSDERMIQUE
}

/// Represente un utitlisateur de l'application
model User {
  id          String      @id @default(uuid())
  email       String      @unique
  /// @HideField()
  password    String
  role        Role?       @relation(fields: [role_id], references: [id])
  /// @HideField()
  role_id     String?
  name        String
  /// @onDelete(SET NULL)
  folders     Folder[]
  specialties Specialty[]
}

model Specialty {
  id    String @id @default(uuid())
  name  String
  users User[]
}

/// Represente les roles que les utilisateurs peuvent avoir
model Role {
  id    String @id @default(uuid())
  /// @onDelete(SET NULL)
  users User[]
  name  String @unique
}

/// Represente les dossier de patients
model Patient {
  id                  String              @id @default(uuid())
  phone               String
  email               String?             @unique
  name                String
  birthdate           String
  sex                 SEX
  picture             String?
  address             String?
  folders             Folder[]
  /// @onDelete(CASCADE)
  antecedents         AntecedentPatient[]
  /// @onDelete(CASCADE)
  allergies           AllergyPatient[]
  special_indications String[]
  blood_type          BLOODTYPE?
  rhesus              RHESUS?
}

/// Represente les antecedents des differents patients
model Antecedent {
  id          String              @id @default(uuid())
  //type              ANTECEDENTTYPE
  description String              @unique
  /// @onDelete(CASCADE   )
  patients    AntecedentPatient[]
}

model AntecedentPatient {
  id            String      @id @default(uuid())
  antecedent    Antecedent? @relation(fields: [antecedent_id], references: [id])
  /// @HideField()
  antecedent_id String?
  patient       Patient?    @relation(fields: [patient_id], references: [id])
  /// @HideField()
  patient_id    String?
  commentary    String?
  active        Boolean     @default(true)
  created_at    DateTime    @default(now())
}

model Allergy {
  id        String           @id @default(uuid())
  substance String           @unique
  /// @onDelete(CASCADE)
  patients  AllergyPatient[]
}

model AllergyPatient {
  id         String   @id @default(uuid())
  allergy    Allergy? @relation(fields: [allergy_id], references: [id])
  /// @HideField()
  allergy_id String?
  patient    Patient? @relation(fields: [patient_id], references: [id])
  /// @HideField()
  patient_id String?
  commentary String?
  active     Boolean  @default(true)
  created_at DateTime @default(now())
}

/// Represente les sejours des patients
model Folder {
  id              String         @id @default(uuid())
  controls        Folder[]       @relation("FolderToFolder")
  patient         Patient?       @relation(fields: [patient_id], references: [id])
  /// @HideField()
  patient_id      String?
  doctor          User?          @relation(fields: [doctor_id], references: [id])
  /// @HideField()
  doctor_id       String?
  constants       Json[]
  observations    String?
  diagnostics     String?
  type            FOLDERTYPE     @default(EXTERNE)
  prescriptions   Prescription[]
  date_start      DateTime       @default(now())
  date_end        DateTime?
  consultation    Folder?        @relation("FolderToFolder", fields: [consultation_id], references: [id])
  /// @HideField()
  consultation_id String?
  status          FOLDERSTATUS   @default(WAITING)
  acts            ActFolder[]
}

// model FolderProtocol {
//   id          String    @id @default(uuid())
//   folder      Folder?   @relation(fields: [folder_id], references: [id])
//   /// @HideField()
//   folder_id   String?
//   protocol    Protocol? @relation(fields: [protocol_id], references: [id])
//   /// @HideField()
//   protocol_id String?
//   commentary  String?
//   created_at  DateTime  @default(now())
// }

/// Represente les protocols medicaux
model Protocol {
  id            String         @id @default(uuid())
  name          String
  description   String?
  prescriptions Prescription[]
  // folders       FolderProtocol[]
  /// @onDelete(CASCADE)
  acts          ActProtocol[]
}

/// Represente les prescriptions effectuees
model Prescription {
  id            String      @id @default(uuid())
  quantity      Int
  posology      String
  duration      Int         @default(0)
  protocols     Protocol[]
  folders       Folder[]
  medicament    Medicament? @relation(fields: [medicament_id], references: [id])
  /// @HideField()
  medicament_id String?
}

/// Represente les actes effectues
model Act {
  id        String        @id @default(uuid())
  type      ACTTYPE
  category  String?
  wording   String
  /// @onDelete(CASCADE)
  protocols ActProtocol[]
  /// @onDelete(CASCADE)
  folders   ActFolder[]
}

model ActProtocol {
  id          String    @id @default(uuid())
  act         Act?      @relation(fields: [act_id], references: [id])
  protocol    Protocol? @relation(fields: [protocol_id], references: [id])
  /// @HideField()
  act_id      String?
  /// @HideField()
  protocol_id String?
  description String?
  created_at  DateTime  @default(now())
}

model ActFolder {
  id         String   @id @default(uuid())
  act        Act?     @relation(fields: [act_id], references: [id])
  folder     Folder?  @relation(fields: [folder_id], references: [id])
  /// @HideField()
  act_id     String?
  /// @HideField()
  folder_id  String?
  results    Json?
  commentary String?
  intern     Boolean  @default(true)
  status     String   @default("PENDING")
  created_at DateTime @default(now())
}

model Medicament {
  id                  String                  @id @default(uuid())
  name                String?
  voie_administration ADMINISTRATIONROUTE[]
  composition         CompositionMedicament[]
  prescriptions       Prescription[]
}

model CompositionMedicament {
  id          String       @id @default(uuid())
  substance   String?
  medicaments Medicament[]
}

// Data from medicine database

// model Medicament {
//   id                          String                  @id @default(uuid())
//   code_cis                    Int                     @unique
//   denomination                String
//   forme_pharmaceutique        String
//   voie_administration         String?
//   statut_administratif        String?
//   type_procedure_autorisation String?
//   etat_commercialisation      String?
//   date_amm                    DateTime?
//   statut_bdm                  String?
//   numero_autorisation         String?
//   titulaire                   String?
//   surveillance_renforcee      Boolean?
//   compositions                CompositionMedicament[]
//   prescriptions               Prescription[]
// }

// model CompositionMedicament {
//   id                                 String      @id @default(uuid())
//   code_cis                           Int?
//   designation_element_pharmaceutique String?
//   code_substance                     Int?
//   denomination                       String?
//   dosage                             String?
//   reference_dosage                   String?
//   nature_composant                   String?
//   numero_lieur                       Int?
//   medicament                         Medicament? @relation(fields: [code_cis], references: [code_cis])
// }
```

**Comment by unlight** [comment]
`special_indications` has type `String[]`

is this valid?

**Comment by unlight** [comment]
I've checked, and this is valid for postgres.

**Comment by lukadriel7** [comment]
Sorry, I wasn't available
