### ISSUE TITLE
GraphQLError [Object]: Type MoodCount must define one or more fields.

### ISSUE THREAD

**Issue by omarkhatibco** [unlight/prisma-nestjs-graphql#33]
Hi, 

I think I found a bug, I'm not sure but this bug is related to a preview feature `selectRelationCount`.

I think this related to #26.

so I got this error in Terminal.

```bash 
[
  GraphQLError [Object]: Type MoodCount must define one or more fields.
      at SchemaValidationContext.reportError (/Users/okhatib/Documents/GitHub/Memoire-LLC/backend/node_modules/graphql/type/validate.js:86:19)
      at validateFields (/Users/okhatib/Documents/GitHub/Memoire-LLC/backend/node_modules/graphql/type/validate.js:234:13)
      at validateTypes (/Users/okhatib/Documents/GitHub/Memoire-LLC/backend/node_modules/graphql/type/validate.js:207:7)
      at validateSchema (/Users/okhatib/Documents/GitHub/Memoire-LLC/backend/node_modules/graphql/type/validate.js:52:3)
      at graphqlImpl (/Users/okhatib/Documents/GitHub/Memoire-LLC/backend/node_modules/graphql/graphql.js:79:62)
      at /Users/okhatib/Documents/GitHub/Memoire-LLC/backend/node_modules/graphql/graphql.js:28:59
      at new Promise (<anonymous>)
      at Object.graphql (/Users/okhatib/Documents/GitHub/Memoire-LLC/backend/node_modules/graphql/graphql.js:26:10)
      at GraphQLSchemaFactory.<anonymous> (/Users/okhatib/Documents/GitHub/Memoire-LLC/backend/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:49:52)
      at Generator.next (<anonymous>)
]
(node:96606) UnhandledPromiseRejectionWarning: Error: Schema generation error (code-first approach)
    at GraphQLSchemaFactory.<anonymous> (/Users/okhatib/Documents/GitHub/Memoire-LLC/backend/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:51:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/okhatib/Documents/GitHub/Memoire-LLC/backend/node_modules/tslib/tslib.js:114:62)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:96606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:96606) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

my Prisma schema for testing 

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["nApi", "selectRelationCount", "filterJson"]
}

generator nestgraphql {
  provider = "node node_modules/prisma-nestjs-graphql"
  output   = "../src/@generated/"
  reExport = All
}

// generator dbml {
//   provider = "prisma-dbml-generator"
// }

generator docs {
  provider = "node node_modules/prisma-docs-generator"
}

enum UserStatus {
  ACTIVE
  FUTURUSER
  INACTIVE
  INVITED
}

enum FriendshipStatus {
  REQUESTED
  ACCEPTED
  REJECTED
}

model User {
  id String @id @default(cuid())

  // Auth Fields
  /// @HideField({  input: true })
  mobileNumber String  @unique
  /// @HideField({  input: true })
  email        String? @unique
  /// @HideField({ output: true, input: true })
  pin          String?

  // Personal Information
  firstName String?
  lastName  String?
  birthday  DateTime?


  // System Data
  /// @HideField({ output: true, input: true })
  status    UserStatus @default(INACTIVE)
  /// @HideField({  input: true })
  createdAt DateTime   @default(now())
  /// @HideField({  input: true })
  updatedAt DateTime   @updatedAt

  //Associated Profile
  /// @HideField({  input: true })
  profile Profile?

  //Associated Image
  /// @HideField({  input: true })
  profileImage UserFile?


  //Friends - relations n-m
  /// @HideField({  input: true })
  friends  User[] @relation("UserFriendsUser", references: [id])
  /// @HideField({ output: true, input: true })
  friendOf User[] @relation("UserFriendsUser", references: [id])

  //FriendsRequest
  /// @HideField({  input: true })
  sentFriendsRequest     FriendRequest[] @relation("UserSendsFriendRequest")
  /// @HideField({  input: true })
  receivesFriendsRequest FriendRequest[] @relation("UserReceivesFriendRequest")

  //parent and child for FUTURE USER
  /// @HideField({ output: true, input: true })
  parent   User?   @relation("UserParentOfUser", fields: [parentId], references: [id])
  /// @HideField({  input: true })
  children User[]  @relation("UserParentOfUser")
  parentId String?

  // Associated Posts - relations 1-n
  /// @HideField({  input: true })
  posts         Post[] @relation("UserAuthorsPost")
  /// @HideField({ output: true, input: true })
  receivedPosts Post[] @relation("userReceivesPosts")

  // Comments
  /// @HideField({ output: true, input: true })
  comments Comment[]

  // created Moods
  /// @HideField({ input: true })
  moods Mood[]

}

model FriendRequest {
  user     User             @relation("UserSendsFriendRequest", fields: [userId], references: [id])
  userId   String
  friend   User             @relation("UserReceivesFriendRequest", fields: [userId], references: [id])
  friendId String
  status   FriendshipStatus

  @@id([userId, friendId])
}

model Profile {
  id String @id @default(cuid())

  // notification Settings
  notificationStatus    Boolean?  @default(true)
  notificationStartTime DateTime?
  notificationEndTme    DateTime?
  currentMode           String?

  //Extras
  /// @HideField({  input: true })
  tos       DateTime @default(now())
  /// @HideField({  input: true })
  createdAt DateTime @default(now())
  /// @HideField({  input: true })
  updatedAt DateTime @updatedAt

  // Relations
  /// @HideField({ output: true, input: true })
  user   User   @relation(fields: [userId], references: [id])
  userId String @unique

}

model Post {
  id String @id @default(cuid())

  // Type - Content
  content  String?
  location Json?
  youtube  String[]
  spotify  String[]

  // Type - Media
  /// @HideField({  input: true })
  media PostFile[]

  // Extras
  /// @HideField({  input: true })
  createdAt DateTime @default(now())
  /// @HideField({  input: true })
  updatedAt DateTime @updatedAt

  // relations with User
  /// @HideField({  input: true })
  author     User   @relation("UserAuthorsPost", references: [id], fields: [authorId])
  authorId   String
  /// @HideField({  input: true })
  receivedBy User[] @relation("userReceivesPosts", references: [id])

  // Publish Options
  receivedAt     DateTime?
  /// @HideField({  input: true })
  receivedMood   Mood?     @relation(fields: [receivedMoodId], references: [id])
  receivedMoodId String?

  // comments
  /// @HideField({  input: true })
  comments Comment[]

}

model Comment {
  id      String @id @default(cuid())
  // Type - Content
  content String


  /// @HideField({  input: true })
  createdAt DateTime @default(now())
  /// @HideField({  input: true })
  updatedAt DateTime @updatedAt


  //ParentPost
  /// @HideField({ output: true, input: true })
  post   Post   @relation(fields: [postId], references: [id])
  postId String


  // Author
  /// @HideField({  input: true })
  author   User   @relation(references: [id], fields: [authorId])
  authorId String
}

model Mood {
  id String @id @default(cuid())

  // Data
  name String

  //Extras
  /// @HideField({  input: true })
  createdAt DateTime @default(now())
  /// @HideField({  input: true })
  updatedAt DateTime @updatedAt

  /// @HideField({ output: true, input: true })
  author   User?   @relation(fields: [authorId], references: [id])
  authorId String?

  // connection to mood
  /// @HideField({ output: true, input: true })
  posts Post[]
}

model PostFile {
  id  String @id
  url String

  //Extras
  /// @HideField({  input: true })
  createdAt DateTime @default(now())
  /// @HideField({  input: true })
  updatedAt DateTime @updatedAt

  /// @HideField({ output: true, input: true })
  post   Post   @relation(fields: [postId], references: [id])
  postId String
}

model UserFile {
  id  String @id
  url String

  //Extras
  /// @HideField({  input: true })
  createdAt DateTime @default(now())
  /// @HideField({  input: true })
  updatedAt DateTime @updatedAt

  /// @HideField({ output: true, input: true })
  user   User   @relation(fields: [userId], references: [id])
  userId String @unique
}

model Notification {
  id      String  @id @default(cuid())
  content String?

}

```
the problem is here

```
model Mood {
  id String @id @default(cuid())

  // Data
  name String

  //Extras
  /// @HideField({  input: true })
  createdAt DateTime @default(now())
  /// @HideField({  input: true })
  updatedAt DateTime @updatedAt

  /// @HideField({ output: true, input: true })
  author   User?   @relation(fields: [authorId], references: [id])
  authorId String?

  // connection to mood
  /// @HideField({ output: true, input: true })
  posts Post[]
}
```

Because `posts` are hidden in both output and input, it geerate this following type.

```ts
import { Field } from '@nestjs/graphql';
import { ObjectType } from '@nestjs/graphql';
import { Int } from '@nestjs/graphql';
import { HideField } from '@nestjs/graphql';

@ObjectType()
export class MoodCount {
    @HideField()
    posts!: number;
}
```

**Comment by unlight** [comment]
Thanks for bug report. Interesting case. I'm still thinking how to deal with that...
Probably `@HideField({ output: true }) should not affect on fields in aggregate output types

**Comment by omarkhatibco** [comment]
@unlight, Thanks for your fast fixing!
