### ISSUE TITLE
Failing after adding class-validator rules

### ISSUE THREAD

**Issue by carlosmarioroldan** [unlight/prisma-nestjs-graphql#52]
I'm getting a weird error after adding the rule `@Validator.MinLength(3)` from class-validator

```prisma
model User {
  id               String   @id @default(uuid())
  /// @Validator.MinLength(3)
  password         String
  email            String   @unique @db.VarChar(60)
  emailConfirmed   Boolean  @default(false) @map("email_confirmed")
  twoFactorEnabled Boolean  @default(true) @map("two_factor_enabled")
  createdAt        DateTime @default(now()) @map("created_at")
  updatedAt        DateTime @updatedAt @map("updated_at")
  status           Status   @default(ACTIVE)
  role             Role     @default(USER)
  profile          Profile?

  @@map("user")
}
```

When I run `prisma generate` the decorator is added

![image](https://user-images.githubusercontent.com/67707877/134268955-747da806-f3f2-4117-8d43-582b070450ae.png)

But when I try to run the project this error shows up. It doesn't say anything at all

![image](https://user-images.githubusercontent.com/67707877/134268693-701e7a8f-ab58-448b-8e4e-bb80b4f81b06.png)

If I remove the rule, then the error goes away & the project works as expected.

This are my dependencies

![image](https://user-images.githubusercontent.com/67707877/134269214-2010ba68-e26e-4f10-8fef-bcab8ccc2f08.png)

Thanks in advance

**Comment by unlight** [comment]
The criteria that source code generated correctly is command `tsc --noEmit` runs without errors.
Is the second screenshot result of `tsc --watch` ?

**Comment by carlosmarioroldan** [comment]
@unlight I'm not really sure, I've uploaded a repository reproducing this error

https://github.com/carlosmarioroldan/reproduction

**Comment by unlight** [comment]
This error is coming from nestjs build, it uses webpack under the hood.

**Comment by unlight** [comment]
node_modules/@nestjs/cli/actions/build.action.js
![image](https://user-images.githubusercontent.com/301732/134386657-72e11760-d311-4541-8835-773d62428d49.png)

Error stack
```
Error
    at getIdentifierFromName (c:\tmp\reproduction\node_modules\@nestjs\graphql\dist\plugin\utils\ast-utils.js:123:15)
    at Object.getDecoratorName (c:\tmp\reproduction\node_modules\@nestjs\graphql\dist\plugin\utils\ast-utils.js:115:16)
    at c:\tmp\reproduction\node_modules\@nestjs\graphql\dist\plugin\utils\plugin-utils.js:9:91
    at Array.find (<anonymous>)
    at Object.getDecoratorOrUndefinedByNames (c:\tmp\reproduction\node_modules\@nestjs\graphql\dist\plugin\utils\plugin-utils.js:9:49)
    at visitNode (c:\tmp\reproduction\node_modules\@nestjs\graphql\dist\plugin\visitors\model-class.visitor.js:23:50)
    at visitNodes (c:\tmp\reproduction\node_modules\typescript\lib\typescript.js:85211:48)
    at Object.visitEachChild (c:\tmp\reproduction\node_modules\typescript\lib\typescript.js:85676:362)
    at visitNode (c:\tmp\reproduction\node_modules\@nestjs\graphql\dist\plugin\visitors\model-class.visitor.js:18:27)
    at visitNodes (c:\tmp\reproduction\node_modules\typescript\lib\typescript.js:85211:48)
```

**Comment by unlight** [comment]
// nest-cli.json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": ["@nestjs/graphql"]
  }
}

Remove `"plugins": ["@nestjs/graphql"]` from `nest-cli.json`
