### ISSUE TITLE
TypeError: Cannot get matching input type from zero length inputTypes

### ISSUE THREAD

**Issue by Signaturo** [unlight/prisma-nestjs-graphql#96]
Hey!🖖  Please help me I can't figure out what the problem is.🙏
I get an error after installing the package and "npx prisma generate' .

```
npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: 
✔ Generated Prisma Client (3.12.0 | library) to ./node_modules/@prisma/client in 472ms

TypeError: Cannot get matching input type from zero length inputTypes
    at getGraphqlInputType (/home/finity/node_modules/prisma-nestjs-graphql/index.js:518:9)
    at AwaitEventEmitter.inputType (/home/finity/node_modules/prisma-nestjs-graphql/index.js:651:30)
    at AwaitEventEmitter.emitSync (/home/finity/node_modules/await-event-emitter/lib/index.js:136:23)
    at AwaitEventEmitter.argsType (/home/finity/node_modules/prisma-nestjs-graphql/index.js:97:16)
    at AwaitEventEmitter.<anonymous> (/home/finity/node_modules/await-event-emitter/lib/index.js:115:39)
    at Generator.next (<anonymous>)
    at /home/finity/node_modules/await-event-emitter/lib/index.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/home/finity/node_modules/await-event-emitter/lib/index.js:8:12)
    at AwaitEventEmitter.emit (/home/finity/node_modules/await-event-emitter/lib/index.js:108:16)
```

**Сonfiguration in Prisma chema:** 

```
generator nestgraphql {
    provider = "node node_modules/prisma-nestjs-graphql"
    output = "../libs/prisma/src/@generated/prisma-nestjs-graphql"
    fields_Validator_from = "class-validator"
    fields_Validator_input = true
```
    
    
**Environment**
"@prisma/client": "^3.12.0",
"prisma": "^3.12.0",
"prisma-nestjs-graphql": "^15.2.1",
"@nestjs/common": "^8.0.0",
"@nestjs/core": "^8.0.0",
"@nestjs/graphql": "^10.0.8",

I don't know much about the details, maybe it's some conflicting dependencies. 
I am using nx monorepo. Just in case, I attach data from the console when installing the package. Maybe this will help. 
I'm unlikely to be able to reproduce the problem in the sandbox now, because I'm a noob :)
Thanks 🙏
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: jasmine-marbles@0.8.4
npm WARN Found: rxjs@7.4.0
npm WARN node_modules/rxjs
npm WARN   peer rxjs@"^6.5.3 || ^7.4.0" from @angular/cdk@13.2.0
npm WARN   node_modules/@angular/cdk
npm WARN     @angular/cdk@"^13.2.0" from the root project
npm WARN   8 more (@angular/common, @angular/core, @angular/forms, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer rxjs@"^6.5.3" from jasmine-marbles@0.8.4
npm WARN node_modules/jasmine-marbles
npm WARN   jasmine-marbles@"~0.8.4" from @nrwl/angular@13.4.6
npm WARN   node_modules/@nrwl/angular
npm WARN 
npm WARN Conflicting peer dependency: rxjs@6.6.7
npm WARN node_modules/rxjs
npm WARN   peer rxjs@"^6.5.3" from jasmine-marbles@0.8.4
npm WARN   node_modules/jasmine-marbles
npm WARN     jasmine-marbles@"~0.8.4" from @nrwl/angular@13.4.6
npm WARN     node_modules/@nrwl/angular
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: ng-packagr@13.1.3
npm WARN Found: tslib@1.14.1
npm WARN node_modules/ng-packagr/node_modules/tslib
npm WARN   tslib@"^1.9.0" from rxjs@6.6.7
npm WARN   node_modules/ng-packagr/node_modules/rxjs
npm WARN     rxjs@"^6.5.0" from ng-packagr@13.1.3
npm WARN     node_modules/ng-packagr
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer tslib@"^2.3.0" from ng-packagr@13.1.3
npm WARN node_modules/ng-packagr
npm WARN   peerOptional ng-packagr@"^13.0.0" from @angular-devkit/build-angular@13.3.0
npm WARN   node_modules/@angular-devkit/build-angular
npm WARN   1 more (the root project)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: rxjs-for-await@0.0.2
npm WARN Found: rxjs@7.4.0
npm WARN node_modules/rxjs
npm WARN   peer rxjs@"^6.5.3 || ^7.4.0" from @angular/cdk@13.2.0
npm WARN   node_modules/@angular/cdk
npm WARN     @angular/cdk@"^13.2.0" from the root project
npm WARN   8 more (@angular/common, @angular/core, @angular/forms, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer rxjs@"^6.0.0" from rxjs-for-await@0.0.2
npm WARN node_modules/rxjs-for-await
npm WARN   rxjs-for-await@"0.0.2" from @nrwl/angular@13.4.6
npm WARN   node_modules/@nrwl/angular
npm WARN   2 more (@nrwl/node, @nrwl/tao)
npm WARN 
npm WARN Conflicting peer dependency: rxjs@6.6.7
npm WARN node_modules/rxjs
npm WARN   peer rxjs@"^6.0.0" from rxjs-for-await@0.0.2
npm WARN   node_modules/rxjs-for-await
npm WARN     rxjs-for-await@"0.0.2" from @nrwl/angular@13.4.6
npm WARN     node_modules/@nrwl/angular
npm WARN     2 more (@nrwl/node, @nrwl/tao)

```

**Comment by unlight** [comment]
Could you provide your prisma schema or part of the schema which can reproduce the error&
