### ISSUE TITLE
AssertionError [ERR_ASSERTION] : Type has been treated as Model

### ISSUE THREAD

**Issue by masterbater** [unlight/prisma-nestjs-graphql#99]
Generated from instrospection.

```
model mailTimeQueue__ {
  id            String                     @id @default(auto()) @map("_id") @db.ObjectId
  concatSubject Boolean
  isSent        Boolean
  mailOptions   MailTimeQueueMailOptions[]
  sendAt        DateTime                   @db.Date
  template      Boolean
  transport     Int
  tries         Int
  /// Field referred in an index, but found no data to define the type.
  to            Json?
}
```

```
type MailTimeQueueMailOptions {
  attachments MailTimeQueueMailOptionsAttachments[]
  from        String
  subject     String
  text        String
  to          String
}
```

AssertionError [ERR_ASSERTION]: Cannot find model by name MailTimeQueueMailOptions
    at AwaitEventEmitter.modelOutputType (/home/gwapoko/smservernestjs/node_modules/prisma-nestjs-graphql/index.js:1049:25)
    at AwaitEventEmitter.<anonymous> (/home/gwapoko/smservernestjs/node_modules/await-event-emitter/lib/index.js:115:39)
    at Generator.next (<anonymous>)
    at /home/gwapoko/smservernestjs/node_modules/await-event-emitter/lib/index.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/home/gwapoko/smservernestjs/node_modules/await-event-emitter/lib/index.js:8:12)
    at AwaitEventEmitter.emit (/home/gwapoko/smservernestjs/node_modules/await-event-emitter/lib/index.js:108:16)
    at generate (/home/gwapoko/smservernestjs/node_modules/prisma-nestjs-graphql/index.js:2050:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.onGenerate (/home/gwapoko/smservernestjs/node_modules/prisma-nestjs-graphql/index.js:2095:5)

**Comment by unlight** [comment]
Looks like there is a lack in support of mongodb features

**Comment by unlight** [comment]
https://www.prisma.io/docs/concepts/components/prisma-client/composite-types

**Comment by masterbater** [comment]
Thanks it would be great if you could add support for embedded documents.
